config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  devise_for :users, controllers: { registrations: "users/registrations",
    sessions: "users/sessions",
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    invitations: 'users/invitations' }

  resources :users
  resources :accounts
    patch "select/:id", to: "accounts#select", as: "account_select"
    get "billing/:id", to: "accounts#billing", as: "account_billing"
  resources :boxes do
    resources :items
    patch "mark/:id", to: "items#mark", as: "item_mark"
    patch "uncheck/:id", to: "items#uncheck", as: "item_uncheck"
    get "move/:id", to: "items#move", as: "item_move"
  end
  resources :memberships
end

app/models/box.rb
class Box < ApplicationRecord
  has_many :items, dependent: :destroy
  acts_as_tenant :account

  validates :name, presence: true
  validates :name, format: { with:  /\A[A-Za-z0-9\-\s]*\z/ }
end

app/controllers/boxes_controller.rb
require "rqrcode"

class BoxesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_box, only: %i[ show edit update destroy ]
  before_action :set_tenant
  before_action :set_current_account

  def index
    @boxes = Box.all
  end

  def new
    @box = Box.new
    @boxes = Box.all
  end

  def show
    @items = @box.items.order(:created_at)
    qrcode = RQRCode::QRCode.new("https://www.youtube.com/")

      svg = qrcode.as_svg(
        color: "000",
        shape_rendering: "crispEdges",
        module_size: 11,
        standalone: true,
        use_path: true
      )
    @qr = svg
  end

  def create 
    @boxes = @current_account.boxes
    @box = Box.new(box_params)
    
    if @box.save
      qrcode = RQRCode::QRCode.new("#{request.url}/#{@box.id}")

      svg = qrcode.as_svg(
        color: "000",
        shape_rendering: "crispEdges",
        module_size: 11,
        standalone: true,
        use_path: true
      )
      @box.update(qr_code: svg)
      
      redirect_to boxes_path 
      flash[:notice] = "box was successfully created"  
         
    else
      render 'new'     
    end
    
  end

  def destroy
    @box.destroy
    respond_to do |format|
      format.html { redirect_to boxes_url, notice: "Box was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_box
    @box = Box.find(params[:id])
  end

  def box_params
    params.require(:box).permit(:name)
  end

  def set_tenant
    account = Account.find(current_user&.current_tenant_id)
    set_current_tenant(account)
  rescue
    redirect_to accounts_path
  end

  def set_current_account
    @current_account = Account.find_by(id: current_user.current_tenant_id)
  end
end

app/helpers/boxs_helper.rb
module BoxsHelper
end

app/views/boxes/_form.html.erb
<h1>This is the box form</h1>

<% if @current_account.plan=="free" && @boxes.count==1 %>
  <h5>You reached the maximun number of boxes allowed for your plan</h5>
  <%elsif @current_account.plan=="moderate" && @boxes.count==5 %>
    <h5>You reached the maximun number of boxes allowed for your plan</h5>
  <%else%>
    
  <%= form_with model: @box do |form| %>

    <% if @box.errors.any? %>
      <div id="error_explanation">
        <h2 class="red ui header"><%= pluralize(@box.errors.count, "error") %> prohibited this box from being saved:</h2>

        <div class="ui list">
          <% @box.errors.each do |error| %>
            <div class="item">
              <i class="red times circle icon"></i>
              <%= error.full_message %>
            </div>
          <% end %>
        </div> 
      </div>
    <%end%>

    <div class="field">
      <%= form.text_field :name, placeholder:"Box name" %>
    </div>

    <div class="actions">
      <%= form.submit class:"ui primary button"%>
    </div>
  <%end%>
<%end%>

app/views/boxes/index.html.erb
<h1 class="index-title">Boxes index</h1>

<div class="ui centered grid">
  <table class="ui basic table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @boxes.each do |box| %>
        <tr>
          <td><%= box.name %></td>
          <td>
            <%= link_to box do %>
              <i class="large blue eye icon"></i>
            <% end %>
            <%= link_to box, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="large red trash icon"></i>
            <% end %>
          </td>
        </tr>
        
      <% end %>
    </tbody>
  </table>
</div>

<div class="ui centered grid">
  <% if @current_account.plan=="free" && @boxes.count==1 %>
    <h5>You reached the maximun number of boxes allowed for your plan</h5>
    <%elsif @current_account.plan=="moderate" && @boxes.count==5 %>
      <h5>You reached the maximun number of boxes allowed for your plan</h5>
    <%else%>
      <%=button_to "Add box", new_box_path, method: :get, class:"ui inverted green button"%>
  <%end%>
</div>

app/views/boxes/new.html.erb
<h2>Add an box:</h2>
<%= render 'boxes/form' %>

app/views/boxes/show.html.erb
<div class="ui three column grid">
  <h1><%= @box.name %></h1>
  <% @items.each do |item| %>
    <div class="column">
      <div class="ui segment">
        <%= image_tag item.image %>
        <p><%= item.description %></p>
        <% if item.using_by.nil? %>
          <%=link_to "Mark as in use", box_item_mark_path(@box,item), method: :patch %><br/>
          <%=link_to "Move", box_item_move_path(@box,item) %><br/>
           <%= link_to box_item_path(@box,item), method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="large red trash icon"></i>
            <% end %>
          <%else%>
            <%if item.using_by==current_user.id%>
              <%=link_to "Uncheck", box_item_uncheck_path(@box,item), method: :patch %><br/>
              <%else%>
                <h5>This item is been used by <%= User.find_by(id: item.using_by).email %></h5><br/>
            <%end%>
        <%end%>
      </div>
    </div>
  <%end%>
</div>

<div class="ui centered card">
  <%= @box.qr_code.html_safe %>
</div>

<div class="ui centered grid">
  <%=button_to "Add item", new_box_item_path(@box), method: :get, class:"ui inverted green button"%>
</div>