config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  devise_for :users, controllers: { registrations: "users/registrations",
    sessions: "users/sessions",
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    invitations: 'users/invitations' }

  resources :users
  resources :accounts
    patch "select/:id", to: "accounts#select", as: "account_select"
    get "billing/:id", to: "accounts#billing", as: "account_billing"
  resources :boxes do
    resources :items
    patch "mark/:id", to: "items#mark", as: "item_mark"
    patch "uncheck/:id", to: "items#uncheck", as: "item_uncheck"
    get "move/:id", to: "items#move", as: "item_move"
  end
  resources :memberships
end

app/models/account.rb
require 'stripe'

class Account < ApplicationRecord
  include Pay::Billable
  belongs_to :user

  validates :name, presence: true
  validates :name, format: { with:  /\A[A-Za-z0-9\-\s]*\z/ }
  validates :plan, presence: true
  validates :cvc, presence: true, numericality: { only_integer: true }
  validates :card_number, presence: true, numericality: { only_integer: true }

  has_many :boxes, dependent: :destroy
  has_many :memberships, dependent: :destroy

  before_save -> do
    self.card_last4 = self.card_number[-4..-1]
  end

  PRICES = { moderate: 100, unlimited: 500 }

  def self.prices 
    PRICES
  end

  def self.month_options
    Date::MONTHNAMES.compact.each_with_index.map { |name, i| ["#{i+1} - #{name}", i+1] }
  end

  def self.year_options
    (Date.today.year..(Date.today.year+10)).to_a
  end

  Plans = [:free, :moderate, :unlimited]
  STRIPE_PRICES = { moderate: "price_1InTzQHPqdZEH70cmJiVyzv6", unlimited: "price_1InU00HPqdZEH70c48pJpYXP" }

  def update_card(account_params)
    Stripe.api_key = ENV['STRIPE_SECRET']
    price = STRIPE_PRICES[plan.to_sym]
    card_hash = {number: account_params[:card_number], exp_month: account_params[:card_exp_month], exp_year: account_params[:card_exp_year], 
      last4: account_params[:card_number][-4..-1], cvc: account_params[:cvc]}

    token = Stripe::Token::create({card: card_hash})[:id]
    customer = Stripe::Customer.update user.account.stripe_customer_id, source: token
    card = Stripe::Customer.list_sources(customer[:id])[:data].first
      
    self.stripe_id = card[:id]
  end
  
  def subscription()
    Stripe.api_key = ENV['STRIPE_SECRET']
    price = STRIPE_PRICES[plan.to_sym]
    card_hash = {number: user.account.card_number, exp_month: user.account.card_exp_month, 
      exp_year: user.account.card_exp_year, last4: user.account.card_last4, cvc: user.account.cvc}
    token = Stripe::Token::create({card: card_hash})[:id]
    customer = Stripe::Customer.create email: user.email, source: token
    card = Stripe::Customer.list_sources(customer[:id])[:data].first

    self.stripe_id =  card[:id]
    self.stripe_customer_id =  card[:customer]
    self.card_type = card[:brand]
    Stripe::PaymentMethod.create({type: 'card',
                    card: {
                    number: card_hash[:number],
                    cvc: card_hash[:cvc],
                    exp_month: card_hash[:exp_month], 
                    exp_year: card_hash[:exp_year], 
                    last4: card_hash[:card_last4],
                      },
                    })
  
    update(stripe_customer_id: customer[:id])
    Stripe::Subscription.create({
      customer: customer[:id],
      items: [
        {price: price},
      ],
    })
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_account, only: %i[ select show edit update destroy billing]
  before_action :set_current_account

  def index
    @accounts = current_user.accounts
    @memberships = current_user.memberships
  end

  def billing
    Stripe.api_key = ENV['STRIPE_SECRET']

    @charges = Stripe::Charge.list({customer: @current_account.stripe_customer_id})[:data]
    @subscription = Stripe::Subscription.list({customer: @current_account.stripe_customer_id, limit: 1})[:data].first
    
  end

  def select 
    current_user.update(current_tenant_id: params[:id])
    redirect_to boxes_path
  end

  def new
    @account = current_user.accounts.new
  end

  def create 
    @account = current_user.accounts.create(account_params)
    if @account.save
      redirect_to users_path
      @membership = Membership.new(user_id: current_user.id, account_id: @account.id)
      @membership.save
      flash[:notice] = "account created successfully"

    else
      render 'users#index'
    end
  end

  private

    def set_account
      @account = Account.find(params[:id])
    end

    def account_params
      params.require(:account).permit(:name, :subdomain, :plan, :card_number, :card_expires, :cvc, :card_exp_month, :card_exp_year)
    end

    def set_current_account
      @current_account = Account.find_by(id: current_user.current_tenant_id)
    end
    
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<h1>This is the contact form</h1>

<div class="ui centered grid">
  <div>
    <%= form_with model: @account do |form| %>
      <% if @account.errors.any? %>
        <div id="error_explanation">
          <h2 class="red ui header"><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

          <div class="ui list">
            <% @account.errors.each do |error| %>
              <div class="item">
                <i class="red times circle icon"></i>
                <%= error.full_message %>
              </div>
            <% end %>
          </div> 
        </div>
      <%end%>
      <div class="ui form">
        <h4 class="ui dividing header">Account information</h4>

        <div class="field">
          <label>Name</label>
          <div class="three fields">
            <div class="field">
              <%= form.text_field :name, placeholder:"Account name" %>
            </div>
          </div>
        </div>

        <div class="fields">
          <div class="seven wide field">
            <label>Plan</label>
            <%= form.text_field :plan, placeholder:"Plan" %>
          </div>  
        <div>   
      </div>

      <div class="actions">
        <%= form.submit class:"ui primary button"%>
      </div>
    <%end%>
  </div>
</div>

app/views/accounts/billing.html.erb
<h1 class="index-title">Billing account info</h1>

<div class="ui centered grid">
  <div>
    <table class="ui very basic collapsing celled table">

      <thead>
        <tr><th>Card information</th>
        <th>Product price</th>
        <th>Next paymente date</th>
      </tr></thead>

      <tbody>
        <tr>
          <td>
            <div class="content">
            <%= @current_account.card_type %>
              <div class="sub header"> *****<%= @account.card_last4 %> </div>
            </div>
          </td>
          <td>
            <%= number_to_currency(Account.prices[@account.plan.to_sym]/100) %>/month
          </td>
          <td>
            <%= to_date(@subscription[:current_period_end].to_s) %>
          </td>
        </tr>
      </tbody>
    </table>

    <table class="ui very basic collapsing celled table">
      <thead>
        <tr>
          <th> Amount (USD) </th>
          <th> Payment Date  </th>
          <th> Product type </th>
        </tr>
      </thead>
      <tbody>
        <% @charges.each do |charge| %>
          <tr>
            <td><%= number_to_currency(charge[:amount]/100) %> </td>
            <td><%= to_date(charge[:created].to_s) %></td>
            <td><%= charge[:description] %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/accounts/index.html.erb
<h1 class="index-title">Availables accounts</h1>
<div class="ui centered grid">

  <table class="ui basic table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Edit payment method</th>
        <th>Billing info</th>
      </tr>
    </thead>
      <tbody>
        <% @memberships.each do |member| %>
          <tr>
            <%if member.account.user_id == current_user.id%>
              <td> <%= link_to  "#{member.account.name} (admin)", account_select_path(member.account), method: :patch %> </td>
              <td> <%= link_to "Edit account", edit_user_registration_path%> </td>
              <% if member.account.plan=="free" %>
                <td>Don't available</td>
                <%else%>
                  <td><%= link_to "See billing info", account_billing_path(member.account) %></td>
              <%end%>

              <%else%>
                <td><%= link_to  member.account.name, account_select_path(member.account), method: :patch %></td>
                <td>Don't available</td>
                <td>Don't available</td>
            <%end%>   
          </tr>  
        <% end %>     
      </tbody>
  </table>
</div>

app/views/accounts/new.html.erb
<h2>Add an account:</h2>
<%= render 'form' %>

app/views/accounts/show.html.erb
<h1><%= @account.name %></h1>

<h2>Boxes</h2>

<%= link_to 'Create new box', new_box_path %>
<ul>
  <% @boxes.each do |box| %>
    <li>
      <%= link_to box.name, box %> 
    </li>
  <% end %>
</ul>